var that=this;function __skpm_run(e,t){that.context=t;var n=function(e){var t={};function n(r){if(t[r])return t[r].exports;var a=t[r]={i:r,l:!1,exports:{}};return e[r].call(a.exports,a,a.exports,n),a.l=!0,a.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var a in e)n.d(r,a,function(t){return e[t]}.bind(null,a));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/generate.js")}({"./src/generate.js":
/*!*************************!*\
  !*** ./src/generate.js ***!
  \*************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t);var r=n(/*! sketch */"sketch"),a=n.n(r),l=n(/*! sketch/dom */"sketch/dom"),o=n.n(l),u=a.a.getDocuments()[0],i=u.pages[0],c=u?u.selectedLayers.layers:null,s=[],f=[],y=[];t.default=function(e){u=a.a.fromNative(e.document),c?(i=0==(i=u.pages.filter(function(e){return"Styles"==e.name})).length?new o.a.Page({parent:u,name:"Styles"}):i[0],c.forEach(function(e){"Text"==e.type?s.push(e):"ShapePath"==e.type&&f.push(e)}),h()):a.a.UI.message("Nothing selected 🤦‍♀️")};var h=function(){0!=s.length?(0==f.length?s.forEach(function(e){d(e)}):s.forEach(function(e){p(e)}),b()):a.a.UI.message("Please select at least one text layer 🕵️‍♂️")},p=function(e){f.forEach(function(t){m(e,t)})},d=function(e){m(e)},m=function(e,t){g(e,t,"01 Left"),g(e,t,"02 Right"),g(e,t,"03 Center")},g=function(e,t,n){var r=e.name;r=(r=r.includes("{align}")?r.replace("{align}",n):r+"/"+n).includes("{color}")&&t?r.replace("{color}",t.name):r.includes("{color}")?r.replace("{color}","Default"):t?r+"/"+t.name:r,y.push({textLayer:e,shapeLayer:t,name:r})},b=function(){y.forEach(function(e){v(e.name,e.textLayer,e.shapeLayer)})},v=function(e,t,n){var r=i.layers.filter(function(t){return t.name==e})[0];r?r.style=t.style:r=new o.a.Text({parent:i,text:e,name:e,style:t.style,frame:{x:0,y:i.layers.length>0?i.layers[i.layers.length-1].frame.y+i.layers[i.layers.length-1].frame.height+20:0}}),e.includes("01 Left")?r.alignment="left":e.includes("02 Right")?r.alignment="right":e.includes("03 Center")&&(r.alignment="center");var a=n&&n.style.fills[0]?n.style.fills[0].color:t.style._object.primitiveTextStyle().attributes().MSAttributedStringColorAttribute;a=n?S(a):x(a);var l=MSImmutableColor.colorWithSVGString_(n.style.fills[0].color),c=MSColor.alloc().initWithImmutableObject_(l);r.sketchObject.setTextColor(c),console.log(c);var s=u.getSharedTextStyles().filter(function(t){return t.name==e})[0];s?s.style=r.style:s=o.a.SharedStyle.fromStyle({name:e,style:r.style,document:u})},S=function(e){if(e){var t=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(e);return t?{r:parseInt(t[1],16)/255,g:parseInt(t[2],16)/255,b:parseInt(t[3],16)/255,a:parseInt(t[4],16)/255}:null}},x=function(e){if(e)return{r:e.red(),g:e.green(),b:e.blue(),a:e.alpha()}}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/dom")}});"default"===e&&"function"==typeof n?n(t):n[e](t)}that.onRun=__skpm_run.bind(this,"default");